os:
  - linux

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

addons:
  apt_packages:
    - pandoc

install:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction

script:
  - make build
  - make phive
  - make dist
  - make install
  - make uninstall
  - make clean

matrix:
  allow_failures:
    - php: nightly

notifications:
  email:
    on_success: never
    on_failure: always
