build: false

platform:
  - x64

clone_depth: 5

environment:
  matrix:
  - PHP_VERSION: '7.0'
    XDEBUG_VERSION: '2.6.0-7.0-vc14-nts-x86_64'
  - PHP_VERSION: '7.1'
    XDEBUG_VERSION: '2.6.0-7.1-vc14-nts-x86_64'
  - PHP_VERSION: '7.2'
    XDEBUG_VERSION: '2.6.0-7.2-vc15-nts-x86_64'

cache:
  - '%LOCALAPPDATA%\Composer\files -> composer.lock'
  - composer.phar
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - c:\tools\php -> appveyor.yml

init:
  - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1
  - SET ANSICON=121x90 (121x90)

install:
  - IF EXIST c:\tools\php (SET PHP=0)
  - ps: appveyor-retry cinst --params '""/InstallDir:C:\tools\php""' --ignore-checksums -y php --version ((choco search php --exact --all-versions -r | select-string -pattern $env:PHP_VERSION | sort { [version]($_ -split '\|' | select -last 1) } -Descending | Select-Object -first 1) -replace '[php|]','')
  - cd c:\tools\php
  - IF %PHP%==1 copy php.ini-production php.ini /Y
  - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
  - IF %PHP%==1 echo extension_dir=ext >> php.ini
  - IF %PHP%==1 echo extension=php_bz2.dll >> php.ini
  - IF %PHP%==1 echo extension=php_curl.dll >> php.ini
  - IF %PHP%==1 echo extension=php_fileinfo.dll >> php.ini
  - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
  - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
  - IF %PHP%==1 echo extension=php_xsl.dll >> php.ini
  - IF %PHP%==1 curl -fsS -o c:\tools\php\ext\php_xdebug-%XDEBUG_VERSION%.dll https://xdebug.org/files/php_xdebug-%XDEBUG_VERSION%.dll
  - IF %PHP%==1 echo zend_extensio=php_xdebug-%XDEBUG_VERSION%.dll >> php.ini
  - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat
  - appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar
  - cd %APPVEYOR_BUILD_FOLDER%
  - appveyor-retry composer install --no-progress --profile

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - composer win-ci
  - php bin/idoitcli.php --help
  - php bin/idoitcli.php --version

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
